#!/usr/bin/env python3
# rebuild-index.py — Rebuild registry/index.md from actual vault files
#
# Usage: python3 scripts/rebuild-index.py

import sys
import re
from pathlib import Path
from datetime import date

try:
    import yaml
    HAVE_YAML = True
except ImportError:
    HAVE_YAML = False

VAULT_ROOT = Path(__file__).parent.parent
INDEX_PATH = VAULT_ROOT / "registry" / "index.md"

SKIP_PARTS = {".git", ".obsidian", ".opencode", "__pycache__", ".venv", "venv", "node_modules", "templates", "schemas", "evaluations", "system", "examples"}
SKIP_DIRS_IN_EVIDENCE = {"raw", "traces"}

LINK_RE = re.compile(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]")


def parse_frontmatter(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not m:
        return {}, ""
    try:
        return (yaml.safe_load(m.group(1)) or {}), m.group(2)
    except Exception:
        return {}, m.group(2)


def first_summary_line(body):
    """Extract a one-line summary from the body, stripping wikilinks."""
    for line in body.split("\n"):
        line = line.strip()
        if line and not line.startswith("#") and not line.startswith("---") and not line.startswith("[["):
            # Strip wikilinks and markdown emphasis for a clean summary
            clean = re.sub(r'\[\[([^\]|]+)(?:\|[^\]]+)?\]\]', r'\1', line)
            clean = re.sub(r'\*\*([^*]+)\*\*', r'\1', clean)
            clean = clean[:100]
            return clean
    return ""


def scan_vault():
    """Walk the vault and categorize pages by directory."""
    categories = {
        "sources": [],
        "source_summaries": [],
        "claims": [],
        "concepts": [],
        "experience_events": [],
        "patterns": [],
        "anti_patterns": [],
        "skills": [],
        "decisions": [],
        "promotions": [],
        "other": [],
    }

    for p in VAULT_ROOT.rglob("*.md"):
        rel = p.relative_to(VAULT_ROOT)
        parts = rel.parts

        # Skip system dirs
        if any(x in SKIP_PARTS for x in parts):
            continue
        # Skip raw captures (immutable, not cataloged)
        if "raw" in parts:
            continue
        # Skip evaluation fixtures
        if "evaluations" in parts:
            continue
        # Skip traces (change-sets are audit artifacts)
        if "traces" in parts:
            continue
        # Skip entity pages (too many, reference-only)
        if "entities" in parts and "global" in parts:
            continue

        fm, body = parse_frontmatter(p)
        stem = rel.stem.lower()
        entry = (stem, rel, fm, body)

        rel_str = rel.as_posix()

        if rel_str.startswith("evidence/sources/"):
            categories["sources"].append(entry)
        elif rel_str.startswith("evidence/source-summaries/"):
            categories["source_summaries"].append(entry)
        elif rel_str.startswith("evidence/claims/"):
            categories["claims"].append(entry)
        elif "experience-events" in rel_str:
            categories["experience_events"].append(entry)
        elif "decisions" in rel_str:
            categories["decisions"].append(entry)
        elif rel_str.startswith("concepts/") or "domains/" in parts[:2] and "concepts" in parts:
            categories["concepts"].append(entry)
        elif rel_str.startswith("patterns/"):
            categories["patterns"].append(entry)
        elif rel_str.startswith("anti-patterns/"):
            categories["anti_patterns"].append(entry)
        elif rel_str.startswith("skills/"):
            categories["skills"].append(entry)
        elif rel_str.startswith("registry/promotions/"):
            categories["promotions"].append(entry)
        elif rel.name in ("index.md", "log.md", "README.md", "CONTRIBUTING.md", "AGENTS.md"):
            continue  # skip hubs and meta files
        else:
            categories["other"].append(entry)

    return categories


def build_index(categories):
    today = date.today().isoformat()
    lines = [
        "---",
        "type: index",
        "title: Vault Index",
        f"updated: {today}",
        "---",
        "",
        "# Index",
        "",
        "Exhaustive catalog. Auto-generated by `scripts/rebuild-index.py`.",
        "",
    ]

    def section(title, entries, key_name=""):
        if not entries:
            return
        lines.append(f"## {title}")
        lines.append("")
        for stem, rel, fm, body in sorted(entries, key=lambda x: x[0]):
            # Get a summary line
            if fm.get("statement"):
                summary = fm["statement"][:100]
            elif fm.get("observed_problem"):
                summary = fm["observed_problem"][:100]
            elif fm.get("title"):
                summary = fm["title"]
            else:
                summary = first_summary_line(body)
            if key_name:
                lines.append(f"- [[{stem}]] — {summary}")
            else:
                lines.append(f"- [[{stem}]] — {summary}")
        lines.append("")

    section("Sources", categories["sources"])
    section("Source Summaries", categories["source_summaries"])
    section("Claims", categories["claims"])
    section("Concepts", categories["concepts"])
    section("Experience Events", categories["experience_events"])
    section("Decisions", categories["decisions"])
    section("Patterns", categories["patterns"])
    section("Anti-Patterns", categories["anti_patterns"])
    section("Skills", categories["skills"])
    section("Promotion Dossiers", categories["promotions"])
    section("Other", categories["other"])

    # Registry hub links
    lines.append("## Registry")
    lines.append("- [[promotion-queue]] — Promotion pipeline")
    lines.append("- [[pattern-index]] — Promoted patterns")
    lines.append("- [[skill-index]] — Reusable skills")
    lines.append("")

    return "\n".join(lines)


def build_registry_json(categories):
    """Machine-readable registry for agent harnesses and CI (registry/index.json)."""
    import json

    def entry(stem, rel, fm):
        fm = fm or {}
        d = {
            "id": str(fm.get("id") or stem),
            "stem": stem,
            "path": str(rel),
            "type": fm.get("type"),
            "title": fm.get("title"),
        }
        for field in ("status", "maturity", "scope", "confidence", "review_after", "last_verified"):
            v = fm.get(field)
            if v is None:
                continue
            # YAML may parse dates into date objects — normalize to ISO strings
            d[field] = v.isoformat() if hasattr(v, "isoformat") else v
        return d

    pages = []
    for name, entries in categories.items():
        for stem, rel, fm, _body in entries:
            page = entry(stem, rel, fm)
            page["scope"] = (fm or {}).get("scope") or (
                "domain" if rel.as_posix().startswith("domains/")
                else "project" if rel.as_posix().startswith("projects/")
                else "global"
            )
            page["category"] = name
            pages.append(page)

    registry = {
        "generated": date.today().isoformat(),
        "counts": {name: len(entries) for name, entries in sorted(categories.items()) if entries},
        "total": sum(len(v) for v in categories.values()),
        "pages": sorted(pages, key=lambda p: (p["category"] or "", p["stem"])),
    }
    out = VAULT_ROOT / "registry" / "index.json"
    out.write_text(json.dumps(registry, indent=2))
    return out


def main():
    import argparse
    import os
    parser = argparse.ArgumentParser(description="Rebuild registry catalog (index.md + index.json)")
    parser.add_argument("--json", action="store_true", help="Print the JSON registry to stdout instead of writing files")
    parser.add_argument("--root", default=None, help="Fabric root (default: repo parent of this script, or $WIKI_FABRIC_ROOT)")
    args = parser.parse_args()

    global VAULT_ROOT, INDEX_PATH
    VAULT_ROOT = Path(args.root or os.environ.get("WIKI_FABRIC_ROOT", VAULT_ROOT)).resolve()
    INDEX_PATH = VAULT_ROOT / "registry" / "index.md"

    categories = scan_vault()
    index_content = build_index(categories)

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(index_content)
    json_path = build_registry_json(categories)

    total = sum(len(v) for v in categories.values())
    print(f"Rebuilt {INDEX_PATH.relative_to(VAULT_ROOT)} + {json_path.relative_to(VAULT_ROOT)}")
    print(f"  Pages cataloged: {total}")
    for name, entries in sorted(categories.items()):
        if entries:
            print(f"  {name}: {len(entries)}")

    if args.json:
        print(json_path.read_text())


if __name__ == "__main__":
    main()