#!/usr/bin/env python3
# vault-refresh.py — Ensure the Obsidian vault mirrors the fabric's structure.
#
# Usage:
#   python3 scripts/vault-refresh.py [VAULT_PATH]          # refresh (idempotent)
#   python3 scripts/vault-refresh.py [VAULT_PATH] --check  # report only; exit 1 on drift
#
# The vault is symlinks: content freshness is structural (a fabric write is
# visible immediately). This tool guarantees *structural* freshness:
#   1. fixed fabric top-level paths always linked
#   2. per-project overlay.yml views present under projects/<slug>/
#   3. broken symlinks reported
#
# Exit codes: 0 = fresh (or refreshed), 1 = drift detected (--check only).

import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from fabric_config import FABRIC_ROOT, get_config, get_all_repo_names

FIXED_LINKS = [
    "AGENTS.md",
    "README.md",
    "concepts",
    "patterns",
    "anti-patterns",
    "skills",
    "projects",
    "syntheses",
    "registry",
    "domains",
    "evidence/claims",
    "evidence/source-summaries",
]

OVERLAY_VIEW_NAME = "overlay.yml"


def default_vault_path():
    return FABRIC_ROOT.parent / "vault"


def overlay_view_content(slug):
    """Fabric-side view of a project's overlay config: routing + identity as
    YAML. Source of truth remains the project's .wiki-overlay.md; this is a
    generated snapshot for the vault (like registry/catalog.json)."""
    config = get_config()
    rc = __import__("fabric_config").get_repo_config(config, slug)
    if not rc:
        return None
    lines = [f"# Generated view of {slug}'s .wiki-overlay.md (source of truth: project repo)",
             "# Regenerated by: wf vault (or bootstrap). Do not hand-edit.",
             "---"]
    for key in ("project", "namespace", "description", "extract", "synthesize",
                "dossier", "graph_dir"):
        v = rc.get(key)
        if v is not None and not isinstance(v, dict):
            lines.append(f"{key}: {v}")
    routing = rc.get("routing") or {}
    if routing:
        lines.append("routing:")
        for k, v in sorted(routing.items()):
            lines.append(f"  {k}: {v}")
    if rc.get("discovered"):
        lines.append("discovered: true")
    lines.append(f"source_overlay: {rc.get('overlay_path', 'fabric.yaml')}")
    return "\n".join(lines) + "\n"


def refresh(vault_path, check_only=False, quiet=False):
    vault = Path(vault_path).expanduser()
    problems = []
    created = 0

    def _say(msg):
        if not quiet:
            print(msg)

    # 1. fixed top-level links
    for link in FIXED_LINKS:
        target = FABRIC_ROOT / link
        lp = vault / link
        if lp.is_symlink() and not lp.exists():
            # dangling link: target missing (empty content dirs get created)
            if check_only:
                problems.append(f"broken symlink: {lp} -> {os.readlink(lp)}")
                continue
            if not target.exists():
                target.mkdir(parents=True, exist_ok=True)  # recreate empty dir
            lp.unlink()          # remove dangling link before re-linking
            lp.symlink_to(target)
            _say(f"  repaired: {link}")
            created += 1
        elif lp.exists():
            continue
        elif target.exists():
            if check_only:
                problems.append(f"missing link: {lp}")
                continue
            vault.mkdir(parents=True, exist_ok=True)
            lp.parent.mkdir(parents=True, exist_ok=True)  # nested targets (evidence/claims)
            os.symlink(target, lp)
            _say(f"  linked: {link}")
            created += 1
        elif not check_only:
            # neither link nor target: create empty target + link
            target.mkdir(parents=True, exist_ok=True)
            vault.mkdir(parents=True, exist_ok=True)
            os.symlink(target, lp)
            _say(f"  linked (new dir): {link}")
            created += 1
        else:
            problems.append(f"missing link: {lp}")

    # 2. per-project overlay views
    projects_dir = vault / "projects"
    for slug in get_all_repo_names(get_config()):
        if slug == "wiki-fabric":
            continue  # self-repo: overlay view is fabric.yaml itself
        view = overlay_view_content(slug)
        if view is None:
            continue
        ns = FABRIC_ROOT / "projects" / slug
        ns.mkdir(parents=True, exist_ok=True)
        view_path = ns / OVERLAY_VIEW_NAME
        if not view_path.exists() or view_path.read_text() != view:
            if check_only:
                problems.append(f"stale overlay view: {view_path}")
                continue
            view_path.write_text(view)
            _say(f"  overlay view: projects/{slug}/{OVERLAY_VIEW_NAME}")
            created += 1

    # 3. dangling top-level symlinks pointing nowhere (untracked vault entries)
    if vault.exists():
        for entry in vault.iterdir():
            if entry.is_symlink() and not entry.exists() and entry.name not in FIXED_LINKS:
                problems.append(f"broken symlink: {entry} -> {os.readlink(entry)}")

    if problems:
        for p in problems:
            print(f"  drift: {p}", file=sys.stderr)
        if check_only:
            print(f"vault: {len(problems)} drift item(s)")
            return 1
        if not quiet:
            print(f"vault: {len(problems)} drift item(s) repaired")
        return 0
    if not quiet:
        print(f"vault: fresh ({created} item(s) created)" if created else "vault: fresh")
    return 0


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Refresh/verify vault structure")
    parser.add_argument("vault_path", nargs="?", default=None)
    parser.add_argument("--check", action="store_true", help="report drift only; exit 1 if stale")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()
    vault = args.vault_path or default_vault_path()
    return refresh(vault, check_only=args.check, quiet=args.quiet)


if __name__ == "__main__":
    sys.exit(main())